server:
  port: 9002

doctor:
  report:
    headache: bloodPressure
    fever: malaria
    bloodPressure: takesomerest
  sections:
    bloodPressure: beds-section
    malaria: pharmacy-section
    lupus: pharmacy-section