server:
  port: 9005
spring:
  datasource:
    url: jdbc:mysql://localhost/drhouse_hospital?useSSL=false
    username: root
    password: nacs
  jpa:
    hibernate:
      ddl-auto: update
costs:
  takesomerest: 130
  MEDICINE: 13
  antibiotika: 30
  antikoagulans: 40

