server:
  port: 9005
spring:
  datasource:
    url: jdbc:mysql://localhost/drhouse_hospital?useSSL=false
    username: root
    password: nacs
  jpa:
    hibernate:
      ddl-auto: update
costs:
  prices:
    takesomerest: 130.0
    medicine: 13.0
    antibiotika: 30.0
    antikoagulans: 40.0
    painkiller: 40.0